### ISSUE TITLE
About Blender

### ISSUE THREAD

**Issue by szhang963** [yifanlu0227/ChatSim#13]
Hi, I met some problems in blending background rgb and 3d assets.
It is successful when I use your provided scene data to add a traffic cone on the ground.
However, the traffic cone can not be added onto the ground (setting z to 0) when I use my scene data.

The config likes this:
```
cars:
- blender_file: blend_3d_assets/data_assets/Traffic_cone.blend
  insert_pos:
  - 15.0
  - 0.032
  - 0
  insert_rot:
  - 0
  - 0
  - -0.0045
  model_obj_name: Car
  new_obj_name: cone
```
![image](https://github.com/yifanlu0227/ChatSim/assets/38983719/08018947-ab3a-48c7-8341-6390a6e0d01f)

I want to know whether there are some hard codes in blender python scripts for waymo setting, and how can I debug the script in vscode debugger?
Thanks in advance.
Best wishes.
